services:
  app:
    build: .
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_SECRET_KEY=${OPENAI_API_SECRET_KEY}
    ports:
      - '3333:3333'
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:latest
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
